name: amarillo

services:
  amarillo:
    image: ${AMARILLO_IMAGE}
    env_file: ./.env.local
    ports:
      - "8080:80"
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./etc/amarillo/conf/:/app/conf/
      - ./etc/amarillo/conf/config:/app/config
      - ./etc/amarillo/templates/:/app/templates/
      - ./var/amarillo/data/:/app/data/
      - ./var/amarillo/stops/:/app/stops/
    restart: unless-stopped

  amarillo-test:
    image: ${AMARILLO_TEST_IMAGE:-${AMARILLO_IMAGE}}
    env_file: ./.env.local
    ports:
      - "8085:80"
    environment:
      TZ: Europe/Berlin
    volumes:
      # Config is currently shared between amarillo and amarillo-test
      - ./etc/amarillo/conf/:/app/conf/
      - ./etc/amarillo/conf/config:/app/config
      - ./etc/amarillo/templates/:/app/templates/
      - ./var/amarillo/stops/:/app/stops/
      # Custom folders for amarillo test
      - ./var/amarillo-test/data/:/app/data/
    restart: unless-stopped
      
  graphhopper:
    image: ${GRAPHHOPPER_IMAGE}
    ports:
      - "8989:8989"
    command: --host 0.0.0.0
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - ./var/graphhopper:/data
    restart: unless-stopped

